# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gsca < Formula
  desc "Global Steam Command Args - CLI tool to manage Steam game launch options"
  homepage "https://github.com/zerkz/gsca"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zerkz/gsca/releases/download/v1.0.0/gsca_1.0.0_darwin_amd64.tar.gz"
      sha256 "f0ea1251d629dba5c703d6ad08269c4932bd04bc8f5614eca10a69a8c3f0328a"

      def install
        bin.install "gsca"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zerkz/gsca/releases/download/v1.0.0/gsca_1.0.0_darwin_arm64.tar.gz"
      sha256 "0f3dc29db3491b085c8038a102facb9544337fce1a23b80a009e500dbcf788b5"

      def install
        bin.install "gsca"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zerkz/gsca/releases/download/v1.0.0/gsca_1.0.0_linux_amd64.tar.gz"
      sha256 "1d4c59e60c4e08d5c069f0163874624314a5c599e46c737c75421602b86376aa"
      def install
        bin.install "gsca"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zerkz/gsca/releases/download/v1.0.0/gsca_1.0.0_linux_arm64.tar.gz"
      sha256 "354f37031398498815b20ee739460b9eaecf1a0b7b7db48d60197fc3195c6ee4"
      def install
        bin.install "gsca"
      end
    end
  end
end
