# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gsca < Formula
  desc "Global Steam Command Args - CLI tool to manage Steam game launch options"
  homepage "https://github.com/zerkz/gsca"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zerkz/gsca/releases/download/v1.0.0/gsca_1.0.0_darwin_amd64.tar.gz"
      sha256 "57327ccb951f532840703f23e333fe1e9b3dc284e49fd681fdb9c4ec8e968563"

      def install
        bin.install "gsca"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zerkz/gsca/releases/download/v1.0.0/gsca_1.0.0_darwin_arm64.tar.gz"
      sha256 "785d9b3219badc78ed5c74aa4cd4d4a015c249caf4b3bf41949d1dec38cdc32c"

      def install
        bin.install "gsca"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zerkz/gsca/releases/download/v1.0.0/gsca_1.0.0_linux_amd64.tar.gz"
      sha256 "00d354d902fe6fd9287916602295519a96e047b51ac020e6c749864e1ef8f565"
      def install
        bin.install "gsca"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zerkz/gsca/releases/download/v1.0.0/gsca_1.0.0_linux_arm64.tar.gz"
      sha256 "9f2f543a73036cca3321d60373db6be39dfc8ccc252e647fec04da0b7bf6d3f1"
      def install
        bin.install "gsca"
      end
    end
  end
end
