# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gsca < Formula
  desc "Global Steam Command Args - CLI tool to manage Steam game launch options"
  homepage "https://github.com/zerkz/gsca"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zerkz/gsca/releases/download/v1.0.0/gsca_1.0.0_darwin_amd64.tar.gz"
      sha256 "efdf585d485a60385047c09d4d8f7ff2a3680211243fba1a5a62b0b9603efc55"

      def install
        bin.install "gsca"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zerkz/gsca/releases/download/v1.0.0/gsca_1.0.0_darwin_arm64.tar.gz"
      sha256 "945f14c65ace2d2b6a12b94a82a863f36fee13d0a3092652e8ca50b83b794edd"

      def install
        bin.install "gsca"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zerkz/gsca/releases/download/v1.0.0/gsca_1.0.0_linux_amd64.tar.gz"
      sha256 "f7b41bc6dfea8114146071eaf80fb394d7dbc568b626ed2a37948241a4b3ef66"
      def install
        bin.install "gsca"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zerkz/gsca/releases/download/v1.0.0/gsca_1.0.0_linux_arm64.tar.gz"
      sha256 "88ff44443d68583aa2a4410867cf865283d298e14ee8396e58f32e78dc04d2d0"
      def install
        bin.install "gsca"
      end
    end
  end
end
